package com.paymentchain.customer.entities;

import java.io.Serializable;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Transient;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Entity
@Data
public class Customer implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(name = "id",required = false,example = "1",defaultValue = "2",description = "This key is autogenerated, it's not necesary")
    private long customerId;
    @Schema(name = "code",required = true,example = "c54c9",defaultValue = "c54c9",description = "Code to identify transacctions and products of the customer")
    private String code;
    @Schema(name = "Iban",required = true,example = "c54cc90773368a8ef53e7f48e33bc79",defaultValue = "c54cc90773368a8ef53e7f48e33bc79",description = "Id to customer account")
    private String Iban;
    @Schema(name = "names",required = true,example = "John",defaultValue = "John",description = "Customer's name")
    private String names;
    @Schema(name = "surname",required = true,example = "Johnson",defaultValue = "Johnson",description = "Customer's lastname")
    private String surname;
    @Schema(name = "phone",required = true,example = "1234-5678",defaultValue = "1234-5678",description = "Customer's phone numver")
    private String phone;
    @Schema(name = "address",required = true,example = "Santa Ana, El Salvador",defaultValue = "Santa Ana, El Salvador",description = "Customer's address")
    private String address;
    @OneToMany(fetch=FetchType.LAZY, mappedBy = "customer",cascade = CascadeType.ALL,orphanRemoval = true)
    @Schema(name = "products",required = true,example = "[{'id':0,'productId':2,'productName':'Mouse optical'}]",defaultValue = "",description = "Customer's name")
    private List<CustomerProduct> products;
    @Transient
    @Schema(name = "transactions",required = true,example = "[{'accounIban':c54c9,'idTransacction':2}]",defaultValue = "",description = "Customer's name")
    private List<?> transactions;
}
