user:
  role: Developer
  alias: aragon
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true  
  datasource:
    url: jdbc:mysql://localhost:3306/paymentchain
    username: root
    password: 12345